name: gps_path_tracker
description: "GPS Path Tracker is a Flutter project designed to track and display GPS paths. It utilizes the user's location data to provide real-time updates on position, speed, and estimated time of arrival to predefined waypoints."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  latlong2: ^0.9.0
  intl: <0.19.0
  permission_handler: ^11.1.0
  csv: ^5.1.1
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/gps_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/gps_icon.png"
    background_color: "#304195"
    theme_color: "#304195"
  windows:
    generate: true
    image_path: "assets/gps_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/gps_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/pathdata.csv
  fonts:
    - family: DMSans
      fonts:
       - asset: assets/fonts/DMSans-w500.ttf
       - asset: assets/fonts/DMSans-w600.ttf
       - asset: assets/fonts/DMSans-w700.ttf
  # Add any other asset, image, or font files here.
